### ISSUE TITLE
gather_statistics to be an intake.open_parquet() argument

### ISSUE THREAD

**Issue by talebzeghmi** [intake/intake-parquet#13]
https://github.com/dask/dask/issues/5272 forced me to consider surfacing `gather_statistics` as another `intake.open_parquet()` parameter passed along to  `dd.read_parquet()`.  

Use case is when working with ~2k parquet files written by Spark where by default the metadata file is not written.  With `gather_statistics=False` Dask won't read every when gathering metadata, but instead rely on metadata of the 0th file.

**Comment by talebzeghmi** [comment]
Can we release master to pypi with this fix?

**Comment by martindurant** [comment]
Done: https://github.com/conda-forge/intake-parquet-feedstock/pull/2
