### ISSUE TITLE
add link to docs

### ISSUE THREAD

**Issue by raybellwaves** [intake/intake-parquet#22]
docs are here: https://intake-parquet.readthedocs.io/en/latest/?badge=latest

can add this to the top right of the repo home page 
![out](https://user-images.githubusercontent.com/17162724/114597151-72b11980-9c5e-11eb-907d-c4c871dacaac.png)

**Comment by martindurant** [comment]
I put in the URL, but it doesn't look much better...

**Comment by raybellwaves** [comment]
thanks
